### ISSUE TITLE
Enable/Disable tool

### ISSUE THREAD

**Issue by Mr-Anderson-01** [rebelappstudio/accessibility_tools#22]
What:
A toggle to enable and disable the whole tool.

Why:
For example, we have an app with its own debug menu. It would be great to have a toggle to enable and disable the whole tool on a debug build within this debug menu.

I have a branch ready to go

**Comment by tomgilder** [comment]
Hi @Mr-Anderson-01, thanks for getting involved!

Is there a reason you need a specific toggle, could you not do something like this?

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: (context, child) => isDebugFlagEnabled ? AccessibilityTools(child: child) : child,
      home: HomePage(),
    );
  }
}
```

**Comment by SAGARSURI** [comment]
In the readme I see you guys mentioned that it's only available in debug mode and not compiled into release mode. We need some way to allow this in release mode for different environments e.g QA/Stg which we can distribute to designers for reviewing all screens which have accessibility issues

**Comment by aednlaxer** [comment]
Hi @SAGARSURI! Have you found a solution? 

I've got an idea that availability of the tools could be made customizable. There could be a flag that changes behaviour: `defaultBehavior` would make it enabled in debug builds and disabled in release builds. `alwaysOn` could force enable it in any build, `alwaysOff` could force disable it in any build. Developers would be able to choose when tools are available based on app flavor, app state etc.

Is it something you're looking for?

**Comment by aednlaxer** [comment]
I believe [this comment](https://github.com/rebelappstudio/accessibility_tools/issues/22#issuecomment-1378569942) answers the original question. For enabling tools in release mode please see #36
