### ISSUE TITLE
No issues are showing

### ISSUE THREAD

**Issue by Huluk** [rebelappstudio/accessibility_tools#37]
I couldn't get any annotations to show on my app, so I checked out this repository and built the example app. No notifications are showing, either. I tried in both Android Studio and on my Android phone.
Is this maybe a version conflict, or do I need to set any additional flags?

I'm running `flutter run --debug` on the following systems:

macOS Sonoma 14.1.1

Flutter 3.16.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7f20e5d18c (2 days ago) • 2023-11-27 09:47:30 -0800
Engine • revision 22b600f240
Tools • Dart 3.2.1 • DevTools 2.28.3

Android Studio Giraffe | 2022.3.1 Patch 2
Build #AI-223.8836.35.2231.10811636, built on September 14, 2023

Simulator: Pixel 3a API 34 extension level 7 arm64 v8a

Physical Phone: Pixel 4a (5G), Android 14, Build 2023-11-05

**Comment by Huluk** [comment]
Thank you for the fix! Everything works now :)

**Comment by aednlaxer** [comment]
Great to hear that! New version with the fix will be released soon
