### ISSUE TITLE
Expand semantic label checker to images

### ISSUE THREAD

**Issue by phcs971** [rebelappstudio/accessibility_tools#45]
Images should also have semantic labels to ensure accessibility.

There is a property in the `Image` widget called `semanticLabel`, I would believe checking it would be similar to the button one.

**Comment by aednlaxer** [comment]
Hi,

Great idea to improve accessibility of illustrations

**Comment by aednlaxer** [comment]
The release with this checker has been published and available on [pub.dev](https://pub.dev/packages/accessibility_tools/changelog#210)
