### ISSUE TITLE
pubspec version constraints need updating

### ISSUE THREAD

**Issue by TDuffinNTU** [rebelappstudio/accessibility_tools#54]
We're on flutter 3.16.9 and noticed builds were failing when adding this package. It appears that you've already had issues with this before https://github.com/rebelappstudio/accessibility_tools/issues/52 So it might be useful to update your version constraints so flutter picks an older version for outdated flutter builds:

https://github.com/rebelappstudio/accessibility_tools/issues/52#issuecomment-2331628053

I think bumping this to 3.22 should help! Not sure if you can retroactively apply this to previous versions too though...

**Comment by aednlaxer** [comment]
Hi Thomas, thanks for reporting an issue! Let's bump version constrains to 3.22. I'll also bump Dart version to 3.0.0

>Not sure if you can retroactively apply this to previous versions too though...

I'm pretty sure it's impossible :( Would setting specific (older) package version in your `pubspec.yaml` help? Something like `1.0.1` or `2.0.0`?

**Comment by aednlaxer** [comment]
Fixed in #55 and released in [v2.2.2](https://pub.dev/packages/accessibility_tools/changelog#222)

**Comment by TDuffinNTU** [comment]
We've got 2.0.1 working for us with no issue :) Thanks!
