### ISSUE TITLE
use kMinInteractiveDimension and kMinInteractiveDimensionCupertino to define MinimumTapArea static constructors

### ISSUE THREAD

**Issue by TDuffinNTU** [rebelappstudio/accessibility_tools#62]
The flutter framework already defines these minimum tap target areas, which means the ones defined in `minimum_tap_area_checker.dart` may become out of sync if they're updated in future versions of either design language.

The desktop values (28 for both) doesn't appear as a constant that I can find so they may have to remain hardcoded for now.

**Comment by aednlaxer** [comment]
This has been implemented and released in [v2.3.0](https://pub.dev/packages/accessibility_tools/versions/2.3.0)
